### ISSUE TITLE
https everywhere is not working as effectively as the extension from webstore.

### ISSUE THREAD

**Issue by TontyTon** [brave/https-everywhere-builder#11] opened 2019-01-07 15:52 UTC
The integrated version rarely upgrades http to https, but when I use the extension it works more often.

**Comment by diracdeltas** [comment] 2019-01-18 00:38
@TontyTon could you please give us an example of a page where the extension store version does more updates? also what platform are you using?

**Comment by TontyTon** [comment] 2019-01-18 07:40
I observe this on almost all sites. For example go to youtube.com, extension encrypts 7 sites
![extension](https://user-images.githubusercontent.com/35778430/51372151-2c5ac780-1af4-11e9-8faa-bdeab6e56e4c.PNG)

while brave shield on 0 sites
![shield](https://user-images.githubusercontent.com/35778430/51372110-059c9100-1af4-11e9-9cdc-0dda46c7374b.PNG)
 
brave version - 0.58.12 checked on dev too
Windows 10
@diracdeltas

**Comment by diracdeltas** [comment] 2019-01-19 02:53
thanks, i looked and it seems this is a known issue. closing as dupe of https://github.com/brave/brave-browser/issues/1535

**Closed as completed by diracdeltas** 2019-01-19 02:53 UTC
